#! /bin/bash
OEM="samsung"
DEVICE="lt02ltespr"
PRROOT="/media/drivec/john"
MKBOOT="$PRROOT/mkboot/$OEM"
ZIP="$PRROOT/zip/$OEM"
NEWMODS="$ZIP/$DEVICE/boot_flash/system/lib/modules"

echo Copying modules to working dir
find -name '*.ko' -exec cp -av {} $NEWMODS/ \;
echo Copying zImage to working dir
find -name 'zImage' -exec cp -av {} $MKBOOT/$DEVICE/ \;
echo Running mkbootfs and mkbootimg
cd $MKBOOT/$DEVICE
. Bootcm
echo Copying boot.img to Edify zip dir
cp $MKBOOT/$DEVICE/boot.img $ZIP/$DEVICE/boot_flash
