#! /bin/bash

DEVICE="lt02ltespr"
MKBOOT="/home/john/mkboot/samsung"
ZIP="/home/john/zip/samsung"
NEWMODS="$ZIP/$DEVICE/lt02spr_boot/system/lib/modules"

echo "Copying modules to working dir"
find -name '*.ko' -exec cp -av {} $NEWMODS/ \;
echo "Copying zImage to working dir"
find -name 'zImage' -exec cp -av {} $MKBOOT/$DEVICE/ \;
echo "Running mkbootfs and mkbootimg"
cd $MKBOOT/$DEVICE
. Bootcm
echo "Copying boot.img to Edify zip dir"
cp $MKBOOT/$DEVICE/boot.img $ZIP/$DEVICE/lt02spr_boot
