#!/bin/bash

make distclean
export CROSS_COMPILE=/opt/toolchains/arm-eabi-4.7/bin/arm-eabi-
export ARCH=arm
export USE_CCACHE=1

#make lt02lte_extracted_defconfig SELINUX_DEFCONFIG=selinux_defconfig
make cyanogen_lt02lte_defconfig SELINUX_DEFCONFIG=selinux_defconfig
make modules
time make -j16 zImage 2>&1 | tee Kbuild.log

if [ -f "./arch/arm/boot/zImage" ]; then
	`. Kaction_`
	else
	echo "Build error!" &&
	`grep -rns error: ./Kbuild.log`
	fi
